# Data Analysis with NumPy and Pandas:
> My lesson plan outline for Data Analysis with NumPy and Pandas

- toc: true 
- badges: true
- comments: true
- categories: [markdown, dumbtrade]

## Lesson Plan Overview:

#### Job:

- Example of analyzing data using both NumPy and Pandas libraries
- Importing data into NumPy and Pandas Performing basic data analysis tasks such as mean, median, and standard deviation Visualization of data using Matplotlib library

#### How I will complete this

- Start by introducing the basics of data analysis and why it's important

- Explain what NumPy and Pandas are and their roles in data analysis

- Discuss the various methods of importing data into NumPy and Pandas

- Teach the audience how to perform basic data analysis tasks such as mean, median, and standard deviation using both libraries

- Demonstrate real-life examples of analyzing data using both NumPy and Pandas libraries

- Give tips on how to develop efficient data analysis skills with NumPy and Pandas, including online resources for further learning
Wrap up the lesson by summarizing the main points covered and encourage the audience to continue practicing their data analysis skills with NumPy and Pandas.

#### What are NumPys & Pandas?

#### Pandas

- What is it: Pandas is like a virtual spreadsheet for data in Python. It is an open-source data manipulation and analysis library for Python that provides data structures for efficiently storing and manipulating labeled data

- Why it's useful: Pandas makes it easy to manipulate, analyze, and visualize data in Python. It provides powerful tools for cleaning and transforming data, working with missing or inconsistent values, and merging or joining multiple datasets. This makes it useful for a wide range of data analysis tasks, from simple data exploration to advanced statistical modeling. Pandas also integrates with other data analysis and visualization libraries in Python, such as Matplotlib and Seaborn.

#### NumPys

- What is it: NumPy is like a calculator for big numbers in Python. It is a powerful scientific computing library for Python used for calculating mathmatical operations on arrays, this includes algebra.

- Why it's useful: NumPy makes it easy to perform complex mathematical operations on large sets of data in Python. It allows for fast computation and manipulation of arrays.

## Let's Take A Look At Some Examples:

In [ ]:
import numpy as np

# Create two arrays of random integers
array1 = np.random.randint(1, 15, size=(4, 4))
array2 = np.random.randint(1, 15, size=(4, 4))

# Perform basic arithmetic operations
sum = array1 + array2
diff = array1 - array2
product = array1 * array2
quotient = array1 / array2

# Print the arrays and their results
print("Array 1:\n", array1)
print("Array 2:\n", array2)

# TODO: Have classmates print results of the operations

In [1]:
# Finished Code

import numpy as np

# Create two arrays of random integers
array1 = np.random.randint(1, 11, size=(3, 3))
array2 = np.random.randint(1, 11, size=(3, 3))

# Perform basic arithmetic operations
sum = array1 + array2
diff = array1 - array2
product = array1 * array2
quotient = array1 / array2

# Print the arrays and their results
# /n creates a new line
print("Array 1:\n", array1)
print("Array 2:\n", array2)

print("Sum of arrays:\n", sum)
print("Difference of arrays:\n", diff)
print("Product of arrays:\n", product)
print("Quotient of arrays:\n", quotient)

Array 1:
 [[10  8  8]
 [ 9 10  9]
 [ 4  9  9]]
Array 2:
 [[ 8  2  1]
 [ 5  9  9]
 [10  5 10]]
Sum of arrays:
 [[18 10  9]
 [14 19 18]
 [14 14 19]]
Difference of arrays:
 [[ 2  6  7]
 [ 4  1  0]
 [-6  4 -1]]
Product of arrays:
 [[80 16  8]
 [45 90 81]
 [40 45 90]]
Quotient of arrays:
 [[1.25       4.         8.        ]
 [1.8        1.11111111 1.        ]
 [0.4        1.8        0.9       ]]
